% Reads nLines of the desired class from CIFAR-10 batch files and returns the corresponding
% line-first grayscale images, using luminance wheigts (0.3, 0.59, 0.11), line-first data.
% Assumes filenames are 'data_batch_n.mat'
if (nargin != 2)
    error('Wrong # of parameters');
endif
arg_list = argv();
nLines = str2double(arg_list{1});
classNumber = str2double(arg_list{2});
if (isnan(nLines) || nLines == nLines < 0 || nLines > 10000)
    error('Lines must be between 1 and 10000');
endif
if (isnan(classNumber) || classNumber < 0 || classNumber > 9)
    error('Class must be between 0 and 9');
endif
%printf('Lines: %d, class: %d\n', nLines, classNumber);
data=genData(nLines, classNumber);
[m,n] = size(data);
msg =  [ ...
    "# Dataset generated by Roberto Stelling from CIFAR-10\n" ...
    "# First n images from a certain class\n" ...
    "# Images converted to grayscale and features reshaped to line first (32x32)\n" ...
    "# Reference\n" ...
    "# This tech report (Chapter 3) describes the dataset and the methodology followed when collecting it in much greater detail.\n" ...
    "# Please cite it if you intend to use this dataset.\n" ...
    "# Learning Multiple Layers of Features from Tiny Images, Alex Krizhevsky, 2009.\n" ...
    "# http://www.cs.toronto.edu/~kriz/learning-features-2009-TR.pdf\n" ];
printf(msg);
for i = 1:nLines
    printf('%d ', data(i, 1:n-1));
    printf('%d\n', data(i, n));
endfor
%save('-text', ['cif_c' arg_list{2} '_' arg_list{1} '.dat'], 'data');