% Reads nLines of the desired class from CIFAR-10 batch files and returns the corresponding
% line-first grayscale images
% Assumes filenames are 'data_batch_n.mat'

% Basic parameter checking
if (nargin != 2)
    error('Wrong # of parameters');
endif
arg_list = argv();
nLines = str2double(arg_list{1});
classNumber = str2double(arg_list{2});
if (isnan(nLines) || nLines == nLines < 0 || nLines > 10000)
    error('Lines must be between 1 and 10000');
endif
if (isnan(classNumber) || classNumber < 0 || classNumber > 9)
    error('Class must be between 0 and 9');
endif

% Collects data using genData.m
data=genData(nLines, classNumber);
% m is nLines but n is not assumed (although it should be 1024 from grayscale CIFAR-10 data)
[m,n] = size(data);

% Header output
msg =  [ ...
    "# Dataset generated by Roberto Stelling from CIFAR-10\n" ...
    "# First n images from a certain class\n" ...
    "# Images converted to grayscale and features reshaped to line first (32x32)\n" ...
    "# Reference\n" ...
    "# This tech report (Chapter 3) describes the dataset and the methodology followed when collecting it in much greater detail.\n" ...
    "# Please cite it if you intend to use this dataset.\n" ...
    "# Learning Multiple Layers of Features from Tiny Images, Alex Krizhevsky, 2009.\n" ...
    "# http://www.cs.toronto.edu/~kriz/learning-features-2009-TR.pdf\n" ];

% The lines below are slower than Octave save functions but gives
% more control than basic output, performance is not an issue
% Data lines should not have leading nor trailing spaces

% Prints the header (with comments #)
printf('# Date: %s', ctime(time()));
printf(msg);
% Prints the data
for i = 1:nLines
    printf('%d ', data(i, 1:n-1));
    printf('%d\n', data(i, n));
endfor